### ISSUE TITLE
Can this work with Spring Boot also in the Unit Test

### ISSUE THREAD

**Issue by leonj1** [despegar/spark-test#2]
Using the below test I get this error

`Caused by: java.lang.IllegalStateException: This must be done before route mapping has begun`

This is because I have Spark Routes as Beans, which get initialized before the @ClassRule gets executed. I just cannot figure out the wiring to get them to play nice together. 

Doubt it matters, but I also have a need to use dbunit to initialize H2 db, which is why you see that included.

```
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration
@TestExecutionListeners({DependencyInjectionTestExecutionListener.class,
        DbUnitTestExecutionListener.class
})
public class FooTest {

    @Configuration
    @ComponentScan(basePackages = {"com.jose.lotto"})
    static class SomeConfig {

        // getting called before @ClassRule
        @Bean
        public static PropertyPlaceholderConfigurer propConfig() {
            PropertyPlaceholderConfigurer ppc =  new PropertyPlaceholderConfigurer();
            ppc.setLocation(new ClassPathResource("application.properties"));
            return ppc;
        }
    }

    public static class TestControllerTestApplication implements SparkApplication {

        @Override
        public void init() {
            new SimpleTestController(); // a single Route to satisfy the test
        }
    }

    @ClassRule
    public static SparkServer2<FooTest.TestControllerTestApplication> testServer
            = new SparkServer2<>(FooTest.TestControllerTestApplication.class, 4567);;

    @Test
    public void sample() throws Exception {
        SparkClient.UrlResponse response = testServer.getClient().doMethod("GET", "/test", null);
        assertEquals(200, response.status);
        assertEquals("This works!", response.body);
        assertNotNull(testServer.getApplication());
    }
}
```

**Comment by leonj1** [comment]
Closing since I dont think this problem is related to spark-test

**Comment by ferwasy** [comment]
Hi @leonj1. Sorry about my delay in the answer. I'm not an expert in Spring Boot, but I think is a problem with the order of execution of @ClassRule. 
You can use the SparkServer without using the annotation @ClassRule (executing the methods before() and after() manually, although it may seem not very "pretty") or you can try to initialize your beans in a custom JUnit Rule and chain it after SparkServer using [RuleChain](http://www.hascode.com/2012/02/ordering-your-junit-rules-using-a-rulechain/)

**Comment by leonj1** [comment]
No worries. Thanks for the reply. With the help of StackOverflow folks I managed to sort things out. Here is that entry, which also contains a link to a working GitHub project: http://stackoverflow.com/questions/39919316/not-sure-why-this-unit-test-works-spring-configurationcontext-updating-or-creat
