### ISSUE TITLE
cannot Find SparkServer using mvn dependency

### ISSUE THREAD

**Issue by prtiwa** [despegar/spark-test#3]
I used maven dependency to download and run the test, but get 
cannot find symbol
  symbol:   class SparkSServer
When i exploded the downloaded jar , i see that SparkServer is not packaged in the jar but used in test..

jar tvf ~/.m2//repository/com/despegar/spark-test/1.0/spark-test-1.0.jar 
     0 Thu Feb 04 09:10:14 PST 2016 META-INF/
   130 Thu Feb 04 09:10:12 PST 2016 META-INF/MANIFEST.MF
     0 Thu Feb 04 09:10:10 PST 2016 com/
     0 Thu Feb 04 09:10:10 PST 2016 com/despegar/
     0 Thu Feb 04 09:10:10 PST 2016 com/despegar/sparkjava/
     0 Thu Feb 04 09:10:10 PST 2016 com/despegar/sparkjava/test/
  3441 Thu Feb 04 09:10:10 PST 2016 com/despegar/sparkjava/test/TestSparkServer.class
   583 Thu Feb 04 09:10:10 PST 2016 com/despegar/sparkjava/test/SparkTest.class
   613 Thu Feb 04 09:10:10 PST 2016 com/despegar/sparkjava/test/TestSparkClient$UrlResponse.class
  8462 Thu Feb 04 09:10:10 PST 2016 com/despegar/sparkjava/test/TestSparkClient.class
     0 Thu Feb 04 09:10:14 PST 2016 META-INF/maven/
     0 Thu Feb 04 09:10:14 PST 2016 META-INF/maven/com.despegar/
     0 Thu Feb 04 09:10:14 PST 2016 META-INF/maven/com.despegar/spark-test/
  4540 Thu Feb 04 09:10:00 PST 2016 META-INF/maven/com.despegar/spark-test/pom.xml
   105 Thu Feb 04 09:10:12 PST 2016 META-INF/maven/com.despegar/spark-test/pom.properties

**Comment by prtiwa** [comment]
Making SparkServer part of the packagable entity will help run the tests

**Comment by ferwasy** [comment]
Hi! Thanks for the interest in this library.
Please, upgrade your dependency to version 1.1.1, which is the latest and the one in which the example code is based. I wasn't clear in the README.
Regards
Fernando
