### ISSUE TITLE
Custom HttpClient in SparkClient

### ISSUE THREAD

**Issue by rchigvintsev** [despegar/spark-test#5]
First of all thank you for your work!

What if I want to create underlying `HttpClient` with custom settings (for example I need to disable redirect handling)? Maybe it is worth to provide additional constructors in `SparkServer` and `SparkClient` that can take external `HttpClient`.

**Comment by ferwasy** [comment]
@rchigvintsev new version 1.1.3 it's more appropiate?

**Comment by rchigvintsev** [comment]
Thank you for reply.
New version resembles Apache HttpComponents but it still does not solve my issues. Connections created by `openConnection` method follow redirect automatically.
I also need to disable cookie management but it seems that in case of using bare HttpUrlConnection cookie management is disabled by default.

**Comment by ferwasy** [comment]
Are you sure that HttpUrlConnection follows redirects automatically? I made custom tests for the case of 301 status code and that not happens. Besides, I googled information, and all examples use the Location response header in order to make a second http request to follow the redirection. For example: https://www.mkyong.com/java/java-httpurlconnection-follow-redirect-example/

**Comment by rchigvintsev** [comment]
Yes, I'm sure. In mkyong's example `HttpUrlConnection` will not follow redirect to https://www.twitter.com automatically due to security reasons. In my case there is no switching of url schema so after receiving of `302 Found` status code `HttpUrlConnection` makes another request and finally I see the result of redirect. But in mykyong's example I discovered the following method that can disable auto-redirect globally: `HttpURLConnection.setFollowRedirects(false)`
For now that works for me so thank you anyway.
Little offtopic: it may be useful to be able to get current port from `SparkServer`.

**Comment by ferwasy** [comment]
Version 1.1.4 have been released, which uses [http-java-native-client 1.0.3](https://github.com/despegar/http-java-native-client), which allows to set following redirects or not
