### ISSUE TITLE
Add support for HEAD request

### ISSUE THREAD

**Issue by seelmann** [despegar/spark-test#7]
I need support for HEAD request.

I wanted to add `com.despegar.http.client.HeadMethod` to the http-java-native-client but the GitHub URL (https://github.com/despegar/http-java-native-client) does not exist.

**Comment by ferwasy** [comment]
Hi @seelmann, thanks for your comment.
You were right, http-java-native-client was private. Now is public and I've added HEAD method support and a new spark-test release (1.1.6) that includes this HEAD support.
Please test it, any comments will be welcome.
Regards.
